const PRODUCTOS = [
  {
    id: "sal-soluble-plain-ivory",
    nombre: "Sal Soluble Plain Ivory",
    fabricante: "ITACA",
    precioM2: 23.9,
    precioCaja: 34.42,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "sal-soluble-siena",
    nombre: "Sal Soluble Siena",
    fabricante: "ITACA",
    precioM2: 23.9,
    precioCaja: 34.42,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "florim-gold",
    nombre: "Florim Gold",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "mexima-onyx",
    nombre: "Mexima Onyx",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "hexa-onyx-gold",
    nombre: "Hexa Onyx Gold",
    fabricante: "ITACA",
    precioM2: 37,
    precioCaja: 53.28,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "xtreme-negro",
    nombre: "Xtreme Negro",
    fabricante: "ITACA",
    precioM2: 37,
    precioCaja: 53.28,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "saint-laurent",
    nombre: "Saint Laurent",
    fabricante: "ITACA",
    precioM2: 37,
    precioCaja: 53.28,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "nero-marquina",
    nombre: "Nero Marquina",
    fabricante: "ITACA",
    precioM2: 37,
    precioCaja: 53.28,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: true,
    fotoAlt: "negro-marquina"
  },
  {
    id: "hera-dune",
    nombre: "Hera Dune",
    fabricante: "Palo Rosa",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "belfast-gris",
    nombre: "Belfast Gris",
    fabricante: "Palo Rosa",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "block-blanco",
    nombre: "Block Blanco",
    fabricante: "Palo Rosa",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "block-beige",
    nombre: "Block Beige",
    fabricante: "Palo Rosa",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×60 cm",
    piezasPorCaja: 4,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "black-onyx-beauty",
    nombre: "Black Onyx Beauty",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "marquina-gold",
    nombre: "Marquina Gold",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "eagele-nero",
    nombre: "Eagele Nero",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "marquina-black",
    nombre: "Marquina Black",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "body-basald-stone-white",
    nombre: "Body Basald Stone White",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: null,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "ghr-body-archie-bianco",
    nombre: "GHR Body Archie Bianco",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "calacatta-green-endles",
    nombre: "Calacatta Green Endles",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "kachori-gold",
    nombre: "Kachori Gold",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "smoke-gold",
    nombre: "Smoke Gold",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "macline-art-green",
    nombre: "Macline Art Green",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "falconer-aqua",
    nombre: "Falconer Aqua",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "taica-art-aqua",
    nombre: "Taica Art Aqua",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "smoke-aqua",
    nombre: "Smoke Aqua",
    fabricante: "ITACA",
    precioM2: 39,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "torso-bianco",
    nombre: "Torso Bianco",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "statuario-sipani",
    nombre: "Statuario Sipani",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "carrara-grey",
    nombre: "Carrara Grey",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "plain-white",
    nombre: "Plain White",
    fabricante: "ITACA",
    precioM2: 29,
    precioCaja: 41.76,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "negro-marquina-xl",
    nombre: "Negro Marquina XL",
    fabricante: "Palo Rosa",
    precioM2: 49,
    precioCaja: 70.56,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true,
    fotoAlt: "negro-marquina"
  },
  {
    id: "verona-beige",
    nombre: "Verona Beige",
    fabricante: "Palo Rosa",
    precioM2: 35,
    precioCaja: 75.6,
    medidas: "60×120 cm",
    piezasPorCaja: 3,
    cubreM2: 2.16,
    tieneFoto: true
  },
  {
    id: "siena-gold",
    nombre: "Siena Gold",
    fabricante: "Palo Rosa",
    precioM2: 35,
    precioCaja: 50.4,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "medici-gris",
    nombre: "Medici Gris",
    fabricante: "Palo Rosa",
    precioM2: 35,
    precioCaja: 50.4,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: true
  },
  {
    id: "mallorca-gris",
    nombre: "Mallorca Gris",
    fabricante: "Carabobo",
    precioM2: 23,
    precioCaja: 32.66,
    medidas: "59.4×119.4 cm",
    piezasPorCaja: 2,
    cubreM2: 1.42,
    tieneFoto: true
  },
  {
    id: "loira-olivo",
    nombre: "Loira Olivo",
    fabricante: "Domosa",
    precioM2: 35,
    precioCaja: 56.16,
    medidas: "60×120 cm",
    piezasPorCaja: 2,
    cubreM2: 1.44,
    tieneFoto: false
  },
  {
    id: "genova-gris",
    nombre: "Genova Gris",
    fabricante: "Balgres",
    precioM2: 21.11,
    precioCaja: 43.7,
    medidas: "36×48 cm",
    piezasPorCaja: 12,
    cubreM2: 2.07,
    tieneFoto: true
  },
  {
    id: "genova-rosa",
    nombre: "Genova Rosa",
    fabricante: "Balgres",
    precioM2: 19,
    precioCaja: 39.33,
    medidas: "36×48 cm",
    piezasPorCaja: 12,
    cubreM2: 2.07,
    tieneFoto: true
  },
  {
    id: "marble-blue",
    nombre: "Marble Blue",
    fabricante: "Caribe",
    precioM2: 21,
    precioCaja: 38.85,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "carrara-marques",
    nombre: "Carrara Marquez",
    fabricante: "Caribe",
    precioM2: 23,
    precioCaja: 42.55,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "calacatta",
    nombre: "Calacatta",
    fabricante: "Caribe",
    precioM2: 23,
    precioCaja: 42.55,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "anela",
    nombre: "Anela",
    fabricante: "Caribe",
    precioM2: 23,
    precioCaja: 42.55,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "lys-horse",
    nombre: "Lys Horse",
    fabricante: "Caribe",
    precioM2: 21,
    precioCaja: 38.85,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "marmol-brandt-beige",
    nombre: "Mármol Brandt Beige",
    fabricante: "Caribe",
    precioM2: 23,
    precioCaja: null,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "madera-teca-2da",
    nombre: "Madera Teca (2ᵈᵃ)",
    fabricante: "Caribe",
    precioM2: 16,
    precioCaja: 29.6,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true,
    fotoAlt: "madera-teca"
  },
  {
    id: "patagonia",
    nombre: "Patagonia",
    fabricante: "Caribe",
    precioM2: 23,
    precioCaja: 42.55,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: false
  },
  {
    id: "madera-teca-1era",
    nombre: "Madera Teca (1ᵉʳᵃ)",
    fabricante: "Caribe",
    precioM2: 18,
    precioCaja: 33.3,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true,
    fotoAlt: "madera-teca"
  },
  {
    id: "choroni-miel",
    nombre: "Choroní Miel",
    fabricante: "Caribe",
    precioM2: 16,
    precioCaja: 29.6,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
  {
    id: "atenas-beige",
    nombre: "Atenas Beige",
    fabricante: "Caribe",
    precioM2: 21,
    precioCaja: 38.85,
    medidas: "43×43 cm",
    piezasPorCaja: 10,
    cubreM2: 1.85,
    tieneFoto: true
  },
];
