import { FormatoPalmeta, MaterialCeramico } from '../tipos/materiales';

export const FORMATO_120_60: FormatoPalmeta = {
  ancho_metros: 1.20,
  largo_metros: 0.60,
  etiqueta: '1.20m x 0.60m'
};

export const FORMATO_60_60: FormatoPalmeta = {
  ancho_metros: 0.60,
  largo_metros: 0.60,
  etiqueta: '0.60m x 0.60m'
};

export const FORMATO_60_30: FormatoPalmeta = {
  ancho_metros: 0.60,
  largo_metros: 0.30,
  etiqueta: '0.60m x 0.30m'
};

export const FORMATO_30_30: FormatoPalmeta = {
  ancho_metros: 0.30,
  largo_metros: 0.30,
  etiqueta: '0.30m x 0.30m'
};

export const CATALOGO_MATERIALES_MVP: MaterialCeramico[] = [
  {
    id: 'porcelanato-marquina-black',
    nombre: 'Porcelanato Marquina Black',
    marca: 'Importllano',
    categoria: 'piso',
    acabado: 'pulido',
    formato_predeterminado: FORMATO_120_60,
    formatos_disponibles: [FORMATO_120_60, FORMATO_60_60],
    propiedades_pbr: {
      rugosidad: 0.05,
      capa_brillo: 1.0,
      metalicidad: 0.1,
      color_hex: '#111111',
      mapa_normal_intensidad: 0.8
    },
    rendimiento_caja_m2: 1.44,
    unidades_por_caja: 2,
    precio_metro_cuadrado: 22.50,
    descripcion: 'Porcelanato de alto brillo con efecto mármol negro azabache y vetas blancas finas. Ideal para pisos de lujo.',
    patron_textura: 'marquina',
    url_textura: '/texturas/marquina.jpg'
  },
  {
    id: 'ceramica-karisma-azul',
    nombre: 'Cerámica Karisma Azul',
    marca: 'Importllano',
    categoria: 'pared',
    acabado: 'brillante',
    formato_predeterminado: FORMATO_60_30,
    formatos_disponibles: [FORMATO_60_30, FORMATO_60_60],
    propiedades_pbr: {
      rugosidad: 0.15,
      capa_brillo: 0.8,
      metalicidad: 0.05,
      color_hex: '#1e3a8a',
      mapa_normal_intensidad: 0.3
    },
    rendimiento_caja_m2: 1.80,
    unidades_por_caja: 10,
    precio_metro_cuadrado: 14.80,
    descripcion: 'Cerámica esmaltada azul marino con acabado semibrillante. Aporta frescura y distinción a paredes de baño y salpicaderos de cocina.',
    patron_textura: 'karisma',
    url_textura: '/texturas/karisma.jpg'
  },
  {
    id: 'porcelanato-carrara-white',
    nombre: 'Porcelanato Carrara White',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'pulido',
    formato_predeterminado: FORMATO_120_60,
    formatos_disponibles: [FORMATO_120_60, FORMATO_60_60],
    propiedades_pbr: {
      rugosidad: 0.08,
      capa_brillo: 0.9,
      metalicidad: 0.05,
      color_hex: '#F8F9FA',
      mapa_normal_intensidad: 0.4
    },
    rendimiento_caja_m2: 1.44,
    unidades_por_caja: 2,
    precio_metro_cuadrado: 24.00,
    descripcion: 'Porcelanato rectificado de mármol Carrara blanco con suave veteado gris. Otorga máxima amplitud y luminosidad.',
    patron_textura: 'carrara',
    url_textura: '/texturas/carrara.jpg'
  },
  {
    id: 'ceramica-gris-neutro',
    nombre: 'Cerámica Gris Neutro',
    marca: 'Importllano',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    formatos_disponibles: [FORMATO_60_60, FORMATO_30_30],
    propiedades_pbr: {
      rugosidad: 0.60,
      capa_brillo: 0.0,
      metalicidad: 0.0,
      color_hex: '#4A5568',
      mapa_normal_intensidad: 0.2
    },
    rendimiento_caja_m2: 1.44,
    unidades_por_caja: 4,
    precio_metro_cuadrado: 12.50,
    descripcion: 'Cerámica mate con apariencia estilo micro-cemento. Excelente versatilidad para estilos contemporáneos e industriales.',
    patron_textura: 'gris_neutro',
    url_textura: '/texturas/gris.jpg'
  },
  {
    id: 'mbd-v125',
    nombre: 'Blanco Real (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/blanco-real.jpg',
    precio_metro_cuadrado: 12.50,
    propiedades_pbr: {
      color_hex: '#E8E6E1',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-943',
    nombre: 'Volcán Verde (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/volcan-verde.jpg',
    precio_metro_cuadrado: 14.00,
    propiedades_pbr: {
      color_hex: '#A3A69C',
      rugosidad: 0.9,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d102',
    nombre: 'Capri Beige (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'brillante',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/capri-beige.jpg',
    precio_metro_cuadrado: 11.20,
    propiedades_pbr: {
      color_hex: '#D9C8B4',
      rugosidad: 0.2,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-v02',
    nombre: 'NOGAL NATURAL (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/msd-v02.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d104',
    nombre: 'KARISMA OSCURO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-d104.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v124',
    nombre: 'LYS HORSE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v124.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v113',
    nombre: 'CUARZO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v113.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFD700',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v115',
    nombre: 'MARBLE BIANCO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v115.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFFFFF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-d107',
    nombre: 'BARROCO GRIS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/msd-d107.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d78',
    nombre: 'CRONOS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-d78.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#000000',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d101',
    nombre: 'CHORONI (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d101.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msg-634',
    nombre: 'GOTEADO ARENA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/msg-634.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'ml-002',
    nombre: 'AZABACHE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/ml-002.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#000000',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-v61',
    nombre: 'CARIBE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/msd-v61.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d24',
    nombre: 'MARMOL CARRARA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d24.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFFFFF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d25',
    nombre: 'MARMOL TRAVERTINO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d25.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msg-v36',
    nombre: 'SAN MARTIN OSCURO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/msg-v36.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#000000',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v68',
    nombre: 'MARMOL CARRARA GRIS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v68.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'ml-004',
    nombre: 'BLANCO ALPES (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/ml-004.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFFFFF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v100',
    nombre: 'BRECCIA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v100.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v17',
    nombre: 'CARRARA MARQUES (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v17.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFFFFF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v10',
    nombre: 'PRIMAVERA AZUL (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v10.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#0000FF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v83',
    nombre: 'MARMOL CARIBE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v83.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'ml-v04',
    nombre: 'AZABACHE PARED (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/ml-v04.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#000000',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v20',
    nombre: 'CARRARA OCRE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v20.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v105',
    nombre: 'VENANZO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v105.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v110',
    nombre: 'CALACATTA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v110.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v101',
    nombre: 'ANELA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v101.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-802',
    nombre: 'CARRARA OCRE 2 (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-802.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mr-002',
    nombre: 'RÚSTICO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mr-002.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-v100',
    nombre: 'MARKO CONCRETO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/msd-v100.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v61',
    nombre: 'PRATO ROSSO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v61.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFC0CB',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v75',
    nombre: 'COLONIAL COTTO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v75.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v14',
    nombre: 'MONACO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-v14.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d106',
    nombre: 'BABILONIA GRIS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d106.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-d08',
    nombre: 'NOGAL NATURAL PARED (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/msd-d08.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'ml-d08',
    nombre: 'PLANICIE GRIS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/ml-d08.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d98',
    nombre: 'CHORONI ARENA (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d98.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'ml-d10',
    nombre: 'CUBO NIEVE (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/ml-d10.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#FFFFFF',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d02',
    nombre: 'CORCEL NEGRO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-d02.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#000000',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-v78',
    nombre: 'CHORONI MIEL (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mbd-v78.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#F5F5DC',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mr-d02',
    nombre: 'CAICO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/mr-d02.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d21',
    nombre: 'MADERA FRESNO (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d21.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'mbd-d46',
    nombre: 'MADERA TECA GRIS (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'pared',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_30,
    url_textura: '/texturas/mbd-d46.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#808080',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
  {
    id: 'msd-v03',
    nombre: 'MURALLA BROWN (Cerámicas Caribe)',
    marca: 'Ceramicas Caribe',
    categoria: 'piso',
    acabado: 'mate',
    formato_predeterminado: FORMATO_60_60,
    url_textura: '/texturas/msd-v03.jpg',
    precio_metro_cuadrado: 15.00,
    propiedades_pbr: {
      color_hex: '#8B5A2B',
      rugosidad: 0.8,
      metalicidad: 0.0,
      capa_brillo: 1.0,
      mapa_normal_intensidad: 0.0,
    },
  },
];
